-- Add video platform fields to campaigns table
ALTER TABLE campaigns 
ADD COLUMN IF NOT EXISTS "videoUrl" TEXT,
ADD COLUMN IF NOT EXISTS "duration" INTEGER,
ADD COLUMN IF NOT EXISTS "likeCount" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "dislikeCount" INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS "isLive" BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS "streamKey" TEXT,
ADD COLUMN IF NOT EXISTS "channelId" TEXT;